[tool.poetry]
name = "spark-utils"
version = "0.0.0"
description = "Utility classes for comfy Spark job authoriing."
authors = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
maintainers = ['GZU <gzu@ecco.com>', 'JRB <ext-jrb@ecco.com>']
license = 'MIT'
readme = "README.md"
repository = 'https://github.com/SneaksAndData/spark-utils'

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
hadoop-fs-wrapper = "~0.7"
cryptography = ">=36"
delta-spark = { version = "~3.2.1", optional = true }
backoff = "~2.2"

kubernetes = { version = "^34", optional = true }

[tool.poetry.extras]
k8s = [
    'kubernetes'
]
delta = [
    'delta-spark'
]

[tool.poetry.dev-dependencies]
pytest = "^9"
pytest-cov = "^7"
pylint = "^4"
black = "^24"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
