name: Validate code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_code:
    name: Validate code in spark container
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}

    container:
      image: esdcrproduction.azurecr.io/spark:v3.1.1-5-g28008d0-bitnami-c31d3b46-python-3.9.16
      credentials:
        username: ${{ secrets.AZCR_PROD_USER }}
        password: ${{ secrets.AZCR_PROD_TOKEN }}
      options: -u root -w /opt/bitnami/spark --mount type=tmpfs,destination=/home/spark

    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          set -e
          
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install Dependencies
        run: |
          set -e
          
          /github/home/.local/bin/poetry install
      - name: Black
        shell: bash
        run: |
          set -e
          /github/home/.local/bin/poetry run black . --check --diff
      - name: Lint
        run: |
          set -e

          find ./spark_utils -type f -name "*.py" | xargs /github/home/.local/bin/poetry run pylint
      - name: Unit test
        shell: bash
        run: |
          set -euxo pipefail

          /github/home/.local/bin/poetry run pytest ./test --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=term-missing:skip-covered | tee pytest-coverage.txt
      - name: Publish Code Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./junit/test-results.xml
