on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'create_package' && github.event.issue.state == 'open' }}
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@v0.0.3
        with:
          pypi_repo_url: https://test.pypi.org/legacy/
          pypi_token_username: ${{ secrets.PYPI_TEST_API_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TEST_API_TOKEN }}
      - name: Create package
        uses: SneaksAndData/github-actions/create_package@add_create_package_action
        with:
          pypi_repo_url: ${{ secrets.AZOPS_PYPI_UPLOAD }}
          pypi_token_username: ${{ secrets.AZOPS_PAT_USER }}
          pypi_token: ${{ secrets.AZOPS_PAT }}
          package_name: python_project